dbt_project:
  target: dev

  outputs:
    dev:
      type: duckdb

      path: /opt/airflow/dbt_project/warehouse.duckdb

      extensions:
        - postgres

      attach:
        - path: "dbname=data_warehouse user=airflow password=airflow_rahasia_tim_123 host=postgres port=5432"
          type: postgres
          alias: data_warehouse