sources:
  - name: raw
    schema: raw
    tables:
      - name: src_booking
      - name: src_flight_segment
      - name: src_customer
      - name: src_airport
      - name: src_aircraft
      - name: src_reservation
      - name: src_hotel_stay
      - name: scr_guest_profile
      - name: scr_hotel_property
      - name: scr_room_inventory
      - name: src_currency
      - name: src_payment_method
      - name: src_payment_transaction