name: 'multidimensional_modelling'
version: '1.0.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]

models:
  multidimensional_modelling:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

require-dbt-version: [">=1.5.0", "<2.0.0"]

vars:
  environment: 'dev'