version: 2

models:
  - name: fact_flight
    description: "Fakta aktivitas penerbangan per segmen"
    columns:
      - name: segment_id
        tests: [unique, not_null]
      - name: gross_amount_usd
        tests: [not_null]

  - name: fact_hotel
    description: "Fakta menginap hotel"
    columns:
      - name: stay_id
        tests: [unique, not_null]
      - name: total_accommodation_bill_usd
        tests: [not_null]

  - name: fact_payment_transaction
    description: "Fakta transaksi pembayaran"
    columns:
      - name: payment_id
        tests: [unique, not_null]
      - name: net_amount_usd
        tests: [not_null]

  - name: fact_rental
    description: "Fakta aktivitas rental mobil"
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: total_charge_usd
        tests: [not_null]
